# Generated by sudocode/scripts/generate_cache_metrics.py; do not edit.
SCHEMA_VERSION = 1
SPEC_SHA256 = "9995432ea94e332f35375818af93683e74f5ec4335555ec6a2b84c46005f1a59"

def cache_efficiency(read, write, uncached=0):
    if any(type(value) is not int or value < 0 for value in (read, write, uncached)):
        raise ValueError('cache counts must be nonnegative integers')
    result = {}
    denominator = read + write + uncached
    result["read_share_pct"] = 100.0 * read / denominator if denominator else None
    denominator = read + write + uncached
    result["write_share_pct"] = 100.0 * write / denominator if denominator else None
    denominator = read + write
    result["reuse_pct"] = 100.0 * read / denominator if denominator else None
    return result


def ttl_cost_comparison(read, write, rescued, write_5m, write_1h, read_price):
    import math
    values = (read, write, rescued, write_5m, write_1h, read_price)
    if (any(not math.isfinite(v) or v < 0 for v in values)
            or rescued > write or write_1h <= write_5m or write_5m <= read_price):
        raise ValueError('invalid TTL cost inputs')
    return {
        "cost_5m": ((write * write_5m) + (read * read_price)),
        "cost_1h": (((write - rescued) * write_1h) + ((read + rescued) * read_price)),
        "break_even_ratio": ((write_1h - write_5m) / (write_1h - read_price)),
    }
