"""Generate native and monitoring calculations from spec/cache_metrics.json.

Commit the outputs; building scode never needs Python. --check catches drift.
Ladder vendors the generated Python module with its immutable source and hash.
"""
import argparse
import hashlib
import json
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def expression(node):
    if isinstance(node, str):
        assert node.isidentifier()
        return node
    operator, left, right = node
    assert operator in ('+', '-', '*', '/')
    return f'({expression(left)} {operator} {expression(right)})'


def generated(spec, digest):
    keys = list(spec['cache'])
    rust = [
        '// Generated by scripts/generate_cache_metrics.py; edit spec/cache_metrics.json.',
        'use serde::{Deserialize, Serialize};',
        f'pub const CACHE_METRICS_SCHEMA_VERSION: u32 = {spec["schema_version"]};',
        f'pub const CACHE_METRICS_SPEC_SHA256: &str = "{digest}";',
        '#[derive(Debug, Clone, Copy, PartialEq, Serialize, Deserialize)]',
        'pub struct CacheEfficiency {',
        *(f'    pub {key}: Option<f64>,' for key in keys),
        '}',
        '#[must_use]',
        '#[allow(clippy::cast_precision_loss)]',
        'pub fn cache_efficiency(read: u64, write: u64, uncached: u64) -> CacheEfficiency {',
    ]
    python = [
        '# Generated by sudocode/scripts/generate_cache_metrics.py; do not edit.',
        f'SCHEMA_VERSION = {spec["schema_version"]}',
        f'SPEC_SHA256 = "{digest}"',
        '',
        'def cache_efficiency(read, write, uncached=0):',
        '    if any(type(value) is not int or value < 0 for value in (read, write, uncached)):',
        "        raise ValueError('cache counts must be nonnegative integers')",
        '    result = {}',
    ]
    for key, ratio in spec['cache'].items():
        denominator = ' + '.join(ratio['denominator'])
        rust_denominator = ' + '.join(f'u128::from({name})' for name in ratio['denominator'])
        numerator = ratio['numerator']
        rust.extend([
            f'    let {key}_denominator = {rust_denominator};',
            f'    let {key} = if {key}_denominator == 0 {{',
            '        None',
            '    } else {',
            f'        Some(100.0 * {numerator} as f64 / {key}_denominator as f64)',
            '    };',
        ])
        python.extend([
            f'    denominator = {denominator}',
            f'    result["{key}"] = 100.0 * {numerator} / denominator if denominator else None',
        ])
    rust.extend(['    CacheEfficiency {', *(f'        {key},' for key in keys), '    }', '}', ''])
    python.extend(['    return result', '', ''])
    # The same model is exported for future native reports and current offline tools.
    ttl_keys = list(spec['ttl'])
    rust.extend([
        '#[derive(Debug, Clone, Copy, PartialEq, Serialize, Deserialize)]',
        'pub struct TtlCostComparison {', *(f'    pub {key}: f64,' for key in ttl_keys), '}',
        '#[must_use]',
        '// Price names match the TTL contract: five-minute and one-hour writes.',
        '#[allow(clippy::similar_names)]',
        'pub fn ttl_cost_comparison(',
        '    read: f64, write: f64, rescued: f64,',
        '    write_5m: f64, write_1h: f64, read_price: f64,',
        ') -> Option<TtlCostComparison> {',
        '    if ![read, write, rescued, write_5m, write_1h, read_price]',
        '        .iter().all(|v| v.is_finite() && *v >= 0.0)',
        '        || rescued > write || write_1h <= write_5m || write_5m <= read_price {',
        '        return None;',
        '    }',
        '    Some(TtlCostComparison {',
        *(f'        {key}: {expression(value)},' for key, value in spec['ttl'].items()),
        '    })', '}', '',
    ])
    python.extend([
        'def ttl_cost_comparison(read, write, rescued, write_5m, write_1h, read_price):',
        '    import math',
        '    values = (read, write, rescued, write_5m, write_1h, read_price)',
        '    if (any(not math.isfinite(v) or v < 0 for v in values)',
        '            or rescued > write or write_1h <= write_5m or write_5m <= read_price):',
        "        raise ValueError('invalid TTL cost inputs')",
        '    return {',
        *(f'        "{key}": {expression(value)},' for key, value in spec['ttl'].items()),
        '    }', '',
    ])
    formatted = subprocess.run(
        ['rustfmt', '--edition', '2021', '--emit', 'stdout'],
        input='\n'.join(rust), capture_output=True, text=True, check=True,
    ).stdout
    return {
        ROOT/'rust/crates/engine-core/src/cache_metrics.rs': formatted,
        ROOT/'scripts/cache_metrics.py': '\n'.join(python),
    }


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    raw = (ROOT/'spec/cache_metrics.json').read_bytes().replace(b'\r\n', b'\n')
    outputs = generated(json.loads(raw), hashlib.sha256(raw).hexdigest())
    failed = []
    for path, expected in outputs.items():
        if args.check:
            if not path.exists() or path.read_text(encoding='utf-8') != expected:
                failed.append(str(path.relative_to(ROOT)))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(expected, encoding='utf-8', newline='\n')
    if failed:
        raise SystemExit('Generated cache metrics differ: ' + ', '.join(failed))
    print('cache_metrics_generation_ok')


if __name__ == '__main__':
    main()
