// Generated by scripts/generate_cache_metrics.py; edit spec/cache_metrics.json.
use serde::{Deserialize, Serialize};
pub const CACHE_METRICS_SCHEMA_VERSION: u32 = 1;
pub const CACHE_METRICS_SPEC_SHA256: &str =
    "9995432ea94e332f35375818af93683e74f5ec4335555ec6a2b84c46005f1a59";
#[derive(Debug, Clone, Copy, PartialEq, Serialize, Deserialize)]
pub struct CacheEfficiency {
    pub read_share_pct: Option<f64>,
    pub write_share_pct: Option<f64>,
    pub reuse_pct: Option<f64>,
}
#[must_use]
#[allow(clippy::cast_precision_loss)]
pub fn cache_efficiency(read: u64, write: u64, uncached: u64) -> CacheEfficiency {
    let read_share_pct_denominator = u128::from(read) + u128::from(write) + u128::from(uncached);
    let read_share_pct = if read_share_pct_denominator == 0 {
        None
    } else {
        Some(100.0 * read as f64 / read_share_pct_denominator as f64)
    };
    let write_share_pct_denominator = u128::from(read) + u128::from(write) + u128::from(uncached);
    let write_share_pct = if write_share_pct_denominator == 0 {
        None
    } else {
        Some(100.0 * write as f64 / write_share_pct_denominator as f64)
    };
    let reuse_pct_denominator = u128::from(read) + u128::from(write);
    let reuse_pct = if reuse_pct_denominator == 0 {
        None
    } else {
        Some(100.0 * read as f64 / reuse_pct_denominator as f64)
    };
    CacheEfficiency {
        read_share_pct,
        write_share_pct,
        reuse_pct,
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Serialize, Deserialize)]
pub struct TtlCostComparison {
    pub cost_5m: f64,
    pub cost_1h: f64,
    pub break_even_ratio: f64,
}
#[must_use]
// Price names match the TTL contract: five-minute and one-hour writes.
#[allow(clippy::similar_names)]
pub fn ttl_cost_comparison(
    read: f64,
    write: f64,
    rescued: f64,
    write_5m: f64,
    write_1h: f64,
    read_price: f64,
) -> Option<TtlCostComparison> {
    if ![read, write, rescued, write_5m, write_1h, read_price]
        .iter()
        .all(|v| v.is_finite() && *v >= 0.0)
        || rescued > write
        || write_1h <= write_5m
        || write_5m <= read_price
    {
        return None;
    }
    Some(TtlCostComparison {
        cost_5m: ((write * write_5m) + (read * read_price)),
        cost_1h: (((write - rescued) * write_1h) + ((read + rescued) * read_price)),
        break_even_ratio: ((write_1h - write_5m) / (write_1h - read_price)),
    })
}
