//! `!<command>` bash mode — the renderer-independent half.
//!
//! Typing `! ls -la` at a prompt runs the command in the user's shell right
//! away and records the exchange in the session transcript **without**
//! starting a model turn. The next prompt carries that transcript, so the
//! model can see what the user ran and what came back. The REPL and the ACP
//! server both dispatch through here; each renders the result its own way.
//!
//! Parity reference: `claude-code-best/claude-code`
//! `src/utils/processUserInput/processBashCommand.tsx`. CC wraps the input in
//! `<bash-input>` and the output in `<bash-stdout>` / `<bash-stderr>`, pushes
//! them as user messages preceded by a local-command caveat, and returns
//! `shouldQuery: false`. CC also runs `!` commands with the sandbox disabled
//! ("User-initiated `!` commands run outside sandbox") — the human typed it,
//! so it runs as the human would run it. Both behaviours are mirrored here.

use runtime::{execute_bash, BashCommandInput, BashCommandOutput, ContentBlock};

/// Tag names shared with CC (`src/constants/xml.ts`). Kept identical so a
/// session exported from one tool renders the same in the other.
pub const BASH_INPUT_TAG: &str = "bash-input";
pub const BASH_STDOUT_TAG: &str = "bash-stdout";
pub const BASH_STDERR_TAG: &str = "bash-stderr";
pub const LOCAL_COMMAND_CAVEAT_TAG: &str = "local-command-caveat";

const LOCAL_COMMAND_CAVEAT: &str = "Caveat: The messages below were generated by the user while \
running local commands. DO NOT respond to these messages or otherwise consider them in your \
response unless the user explicitly asks you to.";

/// Recognise a bash-mode line. Returns the command with the leading `!` and
/// surrounding whitespace removed, or `None` when the line is not bash mode.
///
/// A bare `!` (or `!` followed only by whitespace) is not a command; it falls
/// through to the model as ordinary text so a stray keystroke never spawns a
/// shell.
#[must_use]
pub fn parse_bang_command(input: &str) -> Option<&str> {
    let rest = input.trim().strip_prefix('!')?;
    let command = rest.trim();
    (!command.is_empty()).then_some(command)
}

/// Like [`parse_bang_command`], but first skips any leading
/// `<system-reminder>…</system-reminder>` sections a host prepends to the
/// user's text (apeiron sends every ACP prompt as `note\n\n<user text>`), so
/// the `!` the human typed is still recognised. Anything else before the
/// `!` means it is not a bash-mode line.
#[must_use]
pub fn parse_bang_prompt(input: &str) -> Option<&str> {
    const OPEN: &str = "<system-reminder>";
    const CLOSE: &str = "</system-reminder>";
    let mut rest = input.trim_start();
    while let Some(after_open) = rest.strip_prefix(OPEN) {
        let end = after_open.find(CLOSE)?;
        rest = after_open[end + CLOSE.len()..].trim_start();
    }
    parse_bang_command(rest)
}

/// Run `command` the way CC's bash mode does: through the same executor the
/// bash tool uses, sandbox disabled, default tool timeout. Resolves the
/// working directory through the session's workspace-root scope, like the
/// tool does.
pub fn run(command: &str) -> std::io::Result<BashCommandOutput> {
    execute_bash(BashCommandInput {
        command: command.to_string(),
        timeout: None,
        description: None,
        run_in_background: None,
        dangerously_disable_sandbox: Some(true),
        namespace_restrictions: None,
        isolate_network: None,
        filesystem_mode: None,
        allowed_mounts: None,
    })
}

/// What a completed command leaves in the transcript, as text blocks in push
/// order: caveat, input, output. Each block becomes its own user-role
/// message, as in CC.
#[must_use]
pub fn history_blocks(command: &str, stdout: &str, stderr: &str) -> Vec<ContentBlock> {
    [
        format!("<{LOCAL_COMMAND_CAVEAT_TAG}>{LOCAL_COMMAND_CAVEAT}</{LOCAL_COMMAND_CAVEAT_TAG}>"),
        format!(
            "<{BASH_INPUT_TAG}>{}</{BASH_INPUT_TAG}>",
            escape_xml(command)
        ),
        format!(
            "<{BASH_STDOUT_TAG}>{}</{BASH_STDOUT_TAG}><{BASH_STDERR_TAG}>{}</{BASH_STDERR_TAG}>",
            escape_xml(stdout),
            escape_xml(stderr)
        ),
    ]
    .into_iter()
    .map(|text| ContentBlock::Text { text })
    .collect()
}

/// Transcript blocks for a command that could not be spawned at all
/// (CC: `<bash-stderr>Command failed: …</bash-stderr>`).
#[must_use]
pub fn failure_blocks(command: &str, error: &str) -> Vec<ContentBlock> {
    history_blocks(command, "", &format!("Command failed: {error}"))
}

/// Escape the three characters that would otherwise break the wrapping tags.
#[must_use]
pub fn escape_xml(text: &str) -> String {
    text.replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
}

/// Plain-text rendering for hosts without a terminal (ACP clients): the
/// command as a `$` line, then stdout, stderr, and a non-zero exit status,
/// inside one fenced block so a Markdown-rendering client shows it verbatim.
#[must_use]
pub fn render_plain(
    command: &str,
    stdout: &str,
    stderr: &str,
    exit_status: Option<&str>,
) -> String {
    let mut out = String::from("```\n$ ");
    out.push_str(command);
    out.push('\n');
    for stream in [stdout, stderr] {
        let trimmed = stream.trim_end_matches('\n');
        if !trimmed.is_empty() {
            out.push_str(trimmed);
            out.push('\n');
        }
    }
    if let Some(status) = exit_status {
        out.push('[');
        out.push_str(status);
        out.push_str("]\n");
    }
    out.push_str("```\n");
    out
}
